// <auto-generated />
using System;
using ExamSecondTry.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSecondTry.Data.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220613142316_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExamSecondTry.Data.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a40dbfe-52f7-4d47-bfc1-7d7cb6146f2e"),
                            Director = "James Cameron",
                            Length = 3.1400000000000001,
                            Review = "Boring",
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = new Guid("a77d0dbe-033a-449b-b661-57be85bcc471"),
                            Director = "James Cameron",
                            Length = 2.3999999999999999,
                            Review = "Nice",
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = new Guid("4518ad4b-28fc-489f-9fd6-ac25a4b620bd"),
                            Director = "Martin Scorsese",
                            Length = 3.0,
                            Review = "average",
                            Title = "The Wolf Of Wall Street"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
